# Formula template — the published formula is generated by goreleaser
# (see .goreleaser.yaml, brew section) and lives in dncore/homebrew-tap.
# This file documents the shape; do not edit manually on release.
class Wgtun < Formula
  desc "WireGuard orchestrator: Go TUI + root launchd daemon for wireguard-go"
  homepage "https://github.com/dncore/wgtun"
  license "MIT"
  url "https://github.com/dncore/wgtun/releases/download/v0.1.0/wgtun_0.1.0_darwin_arm64.zip"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  depends_on "wireguard-go"

  def install
    bin.install "wgtun"
  end

  service do
    run [opt_bin/"wgtun", "daemon"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path "/var/log/wgtun/daemon.out.log"
    error_log_path "/var/log/wgtun/daemon.err.log"
  end

  test do
    assert_match "wgtun", shell_output("#{bin}/wgtun version")
  end
end